apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: upload-http-route
  namespace: test
spec:
  parentRefs:
    - name: simple-upload
      kind: Server
      group: policy.linkerd.io
  rules:
    - matches:
      - path:
          value: "/"
        method: GET
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: upload-probe-authn
  namespace: test
spec:
  networks:
  - cidr: 0.0.0.0/0
  - cidr: ::/0
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: upload-probe-policy
  namespace: test
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: upload-http-route
  requiredAuthenticationRefs:
    - name: upload-probe-authn
      kind: NetworkAuthentication
      group: policy.linkerd.io
