apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: auth
  namespace: server
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: httpbin
  requiredAuthenticationRefs:
    - name: client
      kind: ServiceAccount
      namespace: client
